dataset: Tiny
res: 64
model: ConvNetD4
device: [0,1,2,3]

ipc: 50
syn_steps: 20
expert_epochs: 2
lr_img: 100
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset/tiny-imagenet-200
ema_decay: 0.995
Iteration: 10000
batch_syn: 1000

# wandb
project: Tiny_ipc50

num_eval: 1
eval_it: 500
skip_first_eva: True

lr_y: 10.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
expansion_end_epoch: 1
batch_train: 128

Sequential_Generation: False
min_start_epoch: 40
max_start_epoch: 70

lr_lr: 0.0001

zca: True

depth_ratio: 0.5
loss_ratio: 0.5